### ISSUE TITLE
Installation step

### ISSUE THREAD

**Issue by redaxmedia** [joshburgess/eslint-config-standard-pure-fp#1]
Hello,

why do you tell people to install:

```
yarn install --dev eslint-config-standard-pure-fp
yarn install --dev eslint-plugin-better
yarn install --dev eslint-plugin-fp
yarn install --dev eslint-plugin-import
yarn install --dev eslint-plugin-promise
yarn install --dev eslint-plugin-standard
```

instead of adding these to the `dependencies` of this project? I mean, if you use the plugins in this standard - it should not be optional and be installed automatically.

**Comment by joshburgess** [comment]
Yeah, fair point. It's just because they're listed as peer dependencies right now.

I haven't updated this package in quite a while. It's pretty out of date right now.

Honestly, it's really just the configs for standard & cleanjs put together. I just made this at one point for myself out of convenience.

**Comment by redaxmedia** [comment]
Looking forward to some updates as I'm new to FP and would like to have a good starting point for React.
